### ISSUE TITLE
image cassée sur la page des articles

### ISSUE THREAD

**Issue by goofy-mdn** [StellarFX/articles#4]
et par ailleurs le texte blanc sur fond coloré c’est peu lisible :)

capture d’écran
![Screenshot_2020-04-26 Accueil](https://user-images.githubusercontent.com/41866949/80315314-fd52fb80-87f6-11ea-8820-25a0ec2dc99f.png)

**Comment by StellarFX** [comment]
Bizzare.. Normalement c'est beaucoup plus lisible : 
(Je suis sur téléphone mais sur PC ça rend pareil)

https://ibb.co/0rXYSXZ

**Comment by StellarFX** [comment]
Ah ! J'ai compris ! 
J'ai réparé la chose et l'ai déplacé au lien suivant :

 https://bloodied-squad.cf/articles/accueil/
